### ISSUE TITLE
Create missing target directory on init

### ISSUE THREAD

**Issue by stramec** [chi-rb/chi-cloud#1]
When you use `cloud init some_app` if the some_app directory has not been previously created the following occurs:

> cloud init some_app
> /usr/local/bin/cloud: line 39: cd: some_app: No such file or directory

The cloud and tmp directories are then created in the current directory. 

Perhaps a check would be nice if the directory exists and if not create it?

**Comment by mmontossi** [comment]
You're right! Should be fixed in the last commit, execute `cloud update` and give it another try.

**Comment by stramec** [comment]
Yep that works great now 👍
